paths:
  /entra/client_info:
    get:
      security:
        - apikeyAuth: []
      responses:
        302:
          description: Success
          schema:
            type: "string"
            
  /entra/authorize:
    get:
      responses:
        302:
          description: Success
          schema:
            type: "string"

  /entra/token:
    post:
      security:
        - apikeyAuth: []
      parameters:
        - in: body
          name: body
          schema:
            $ref: "#/definitions/CommonRequest"
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/CommonResponse"

  /entra/token-refresh:
    post:
      security:
        - apikeyAuth: []
      parameters:
        - in: body
          name: body
          schema:
            $ref: "#/definitions/CommonRequest"
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/CommonResponse"